### PR TITLE
added option to have preProcess ignore non-numeric data

### PR DESCRIPTION
**Pull request by terrytangyuan**
Issue #100

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Could you check to see whether the build was failed by my added code? It looks like something went wrong during resampling and I don't think it relates to my code.

**Comment by zachmayer** [comment]
Builds are failing on master right now due to a weird package installation issue.




I'll put up a fix today and have Travis re run on all open PRs



—

**Comment by topepo** [comment]
I appreciate the work but I have a broader set of changes and those would capture this. 

I've committed a [new version](https://github.com/topepo/caret/commit/399b973d4936523fb1429491421032eb52744028) of `preProcess` and some regression tests. Please give it a try and see if it works for you.

**Comment by terrytangyuan** [comment]
Thanks. Could you close the issues that have been fixed or in progress? If someone started to work on some issues, please also assign them so that I won't look into it. I love this package and I want to contribute as much as I can.

**Pull request closed without merging**
