### PR TITLE
Adding MAE as a standard output for regression tasks

### PR DESCRIPTION
**Pull request by hadjipantelis**
Regression tasks out-of-the-box are showing only RMSE and R^2; [MAE](https://en.wikipedia.org/wiki/Mean_absolute_error) has been added. Given that a lot of algorithms working with L1 norms I think it will be beneficial for users to immediately be able to check absolute errors too. L1 is not some arcane specialised norm and I think adding MAE to the defaults will save valuable time (and potential bugs) for people writing their own cost functions to add MAE-like measures.

### CODE REVIEW

**Comment by topepo** [comment]
Can you add a note on this to `News.Rd`?

**Comment by hadjipantelis** [comment]
There is no section for the next/next release and I am unaware of the version numbering you would like to use. Would you like me to create a section for `Changes in version 6.0-77` and take it from there? Should I change the DESCRIPTION file to indicate 6.0-77 too? (or any other version number is appropriate)

**Comment by topepo** [comment]
> Would you like me to create a section for Changes in version 6.0-77 and take it from there? 

yes. 

> Should I change the DESCRIPTION file to indicate 6.0-77 too? (or any other version number is appropriate)

yes, thanks

**Comment by hadjipantelis** [comment]
No problem. Suggestions implemented.

**Comment by topepo** [comment]
Thanks!

**Comment by danielalthoff** [comment]
Hello.
I've trying adding MBE and NSE as well to the outcome... but couldn't make it happen..
could you help me out please?
Thanks

**Comment by topepo** [comment]
Go ahead and file a separate issue and carefully read the instructions on the issue package to create a reproducible example. Also, in the issue, please define MBE and NSE (nonstandard evaluation?)

**Pull request merged**
