### PR TITLE
Switch to non-formula interface in ranger

### PR DESCRIPTION
**Pull request by mnwright**
Should be faster and more memory efficient

### CODE REVIEW

**Comment by topepo** [comment]
Thanks for the PR. Can you resync and add a note to the NEWS.Rd file about this?

**Comment by mnwright** [comment]
Done. Should the version be increased?

**Comment by topepo** [comment]
Thanks!

**Comment by topepo** [comment]
Nevermind. It was trivial enough to do with the web editor.

**Pull request merged**
