### PR TITLE
Fix direction argument for pROC (#431)

### PR DESCRIPTION
**Pull request by xrobin**
First attempt to address issue #431

### CODE REVIEW

**Comment by zachmayer** [comment]
You should add a testthat test

**Comment by xrobin** [comment]
I guess that means adding tests for the twoClassSummary, multiClassSummary and rocPerCol functions? The last one is internal, do you have any recommendation for the tests?

**Comment by xrobin** [comment]
I pushed a simple test for rocPerCol. It fails with the current version of caret, although I couldn't see it with an R CMD check. I'll add tests for the two other functions later on.

**Comment by topepo** [comment]
Thanks.

**Pull request merged**
