### PR TITLE
zapping issue #587

### PR DESCRIPTION
**Pull request by JackStat**
It seems that it was a naming issue that was pulling in a column named NA

### CODE REVIEW

**Comment by JackStat** [comment]
Yes sir.  https://github.com/topepo/caret/pull/596

**Comment by hadjipantelis** [comment]
Oops, I did not see your pull on time and submitted a much more simplistic fix along with a new model. Thanks for sorting that out! I will close the relevant issue ( #587 ).

**Comment by topepo** [comment]
Just getting to this... 

In this code: 
```r
prob_stats <-
  lapply(levels(data[, "pred"]),
         function(x){
           #Grab one-vs-all data for the class
           obs  <- ifelse(data[,"obs"] == x, 1, 0)
           prob <- data[,x]
           AUCs <- try(ModelMetrics::auc(obs, data[,x]), silent = TRUE)
           return(AUCs)
         })
```
are you sure that the AUC is using the write direction (meaning that if the AUC should be .80 and not reported to be .20)?

**Comment by JackStat** [comment]
I am quite sure that this chunk resolves that issue

```
#Grab one-vs-all data for the class
           obs  <- ifelse(data[,"obs"] == x, 1, 0)
```

In cases where there is no prediction the population AUC is .50. In a sample it will drop below .50 half of the time. Other packages automatically flip it so it is always greater than .50 but the user just needs to make sure that the binary outcome that the probability pertains to is a 1 and the other a 0.

**Comment by topepo** [comment]
> I am quite sure that this chunk resolves that issue

Some test cases with simulated data would help verify that =]

**Comment by JackStat** [comment]
Sure. I will write since up tonight.

**Pull request merged**
