### PR TITLE
fixed travis build file

### PR DESCRIPTION
**Pull request by jtilly**
I fixed the travis build file after seeing your question [here](http://stackoverflow.com/questions/31879011/r-cant-find-packages-installed-by-travis). `R CMD check --as-cran` is looking for packages (that are not explicitly stated as dependency) in `/usr/lib/R/library`. I then use the "old school" travis setup to install dependencies in `/usr/lib/R/library` so they can be found. I'm also installing a bunch of dependent packages as binaries to make the build faster.

### CODE REVIEW

**Comment by zachmayer** [comment]
Thank you for fixing this!  2 requests:

1. Fix merge conflicts.  I was also working on the .travis.yml file, but you can just resolve the conflicts by discarding all changes on master and replacing them with your file.
2. Add the coveralls line back in, and the coveralls install_github:
```{yml}
after_success:
  - Rscript -e 'library(covr);coveralls()'
```

THANKS SO MUCH!  This has been bothering me for weeks.

**Comment by jtilly** [comment]
I fixed the merge conflicts and added coveralls support.

**Comment by zachmayer** [comment]
THANKS!

**Comment by zachmayer** [comment]
Out of curiosity, during `./travis-tool.sh bootstrap`, is it skipping the latex bootstrapping step?  I'd like to avoid latex if possible, as we're skipping manual and vignette building.

**Comment by jtilly** [comment]
Yes, the current version is skipping the latex bootstrapping step. As long as the environmental variable `BOOTSTRAP_LATEX` is not set, no latex distribution will be installed.

**Comment by zachmayer** [comment]
Great.  Thank you!

**Pull request merged**
