### PR TITLE
Allow construction of RBF models for regression.

### PR DESCRIPTION
**Pull request by dratewka**
After adding support for regression type models to RBF networks everything seems to be working fine.

### CODE REVIEW

**Comment by zachmayer** [comment]
Looks good to me.  Have you tested that this works?

**Comment by dratewka** [comment]
Yep, seems to work:

  > devtools::install_github('dratewka/caret/pkg/caret')
  > x <- matrix(seq(-10,10, length=100), ncol=1)
  > y <- sin(x) + rnorm(length(x))
  > m <- caret::train(x,y, method='rbfDDA')
  > mean((y-predict(m,x))^2)
  [1] 1.508441

**Comment by zachmayer** [comment]
@topepo I think you can go ahead and merge this, it looks like a pretty straightforward change.

**Comment by topepo** [comment]
This is relatively untested but it might work:

```r
mnLogLoss <- function(data, lev = NULL, model = NULL){
  eps <- 1e-15
  probs <- as.matrix(data[, lev, drop = FALSE])
  probs[probs > 1 - eps] <- 1 - eps
  probs[probs < eps] <- eps
  inds <- caret:::class2ind(data$obs)
  -mean(apply(inds*log(probs), 1, sum), na.rm = TRUE)
}
```

**Pull request merged**
