### PR TITLE
Add sorted levels to factors (attempt to fix #620)

### LINKED ISSUE #620: ggplot.train level plots has incorrectly reordered axis
It seems that ggplot.train is converting the tuneGrid parameters into factors and thus sometimes creating cases when numerical order is broken. Consequently the charts have incorrect axis order.
e.g. instead of 0.0001, 0.01, 1 it produces 1e-2, 1e-4, 1 (string order not number order).
### Minimal, reproducible example:
```{R}
library(caret)
data(mtcars)
m <- train(mpg ~ cyl + disp,
           data = mtcars,
           method="svmRadial",
           tuneGrid = expand.grid(C=1:2, sigma=c(0.0001, 0.01, 1)))
ggplot(m, plotType="level")
```
the produced chart has incorrectly ordered sigma axes.

### Session Info:
```{R}
>sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] kernlab_0.9-25  caret_6.0-73    ggplot2_2.2.1   lattice_0.20-34

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10       magrittr_1.5       splines_3.3.2      MASS_7.3-45        munsell_0.4.3     
 [6] colorspace_1.3-2   foreach_1.4.3      minqa_1.2.4        stringr_1.2.0      car_2.1-4         
[11] plyr_1.8.4         tools_3.3.2        parallel_3.3.2     nnet_7.3-12        pbkrtest_0.4-7    
[16] grid_3.3.2         gtable_0.2.0       nlme_3.1-131       mgcv_1.8-17        quantreg_5.29     
[21] MatrixModels_0.4-1 iterators_1.0.8    digest_0.6.12      lme4_1.1-12        lazyeval_0.2.0    
[26] assertthat_0.1     tibble_1.2         Matrix_1.2-8       nloptr_1.0.4       reshape2_1.4.2    
[31] ModelMetrics_1.1.0 codetools_0.2-15   labeling_0.3       stringi_1.1.3      compiler_3.3.2    
[36] scales_0.4.1       stats4_3.3.2       SparseM_1.76      
```

### PR DESCRIPTION
**Pull request by m-dz**
If values are numeric add sorted levels to factors to fix ggplot axes values.

### CODE REVIEW

**Comment by m-dz** [comment]
Hi, I have added a few tests for the `ggplot`, both using the passed data and the actual plot labels.

**Comment by topepo** [comment]
Excellent. Thanks for fixing this. Can you also edit the NEWS.Rd file to describe the change and to get recognition for yourself?

**Comment by m-dz** [comment]
It was a pleasure. Hmm, I will give the NEWS.Rd a try as soon as I find it, thanks for letting me know about it.

**Comment by m-dz** [comment]
I have added a reference in NEWS.Rd (of course feel free to change it), thank you for the opportunity.

**Comment by topepo** [comment]
Thanks

**Comment by m-dz** [comment]
There is a test related to this issue/pull request ready, but it take a bit longer to calculate (12-13 s on my extra slow PC) so I have not added it in this PR. Should I? Code is below, it results in `NA`s, but it also produces faceted plot so can test for correct ordering of facets' labels which was also an issue here.

```
x <- train(mpg ~ cyl + disp,
           data = mtcars,
           method="xgbTree",
           tuneGrid = expand.grid(
             nrounds=c(20),
             max_depth=c(2),
             eta = c(0.0001, 0.01, 1),
             gamma = c(0.0001, 0.01, 1),
             colsample_bytree=c(0.0001, 0.01, 1),
             min_child_weight = 1,
             subsample = 1
           ))

ggplot(x, plotType="level", nameInStrip = TRUE)
```

Also, I can add a `\newcommand{\pull}{\href{https://github.com/topepo/caret/pull/#1}{(pull #1)}}` to NEWS.Rd file to refer to pull requests.

**Pull request merged**
