### PR TITLE
Add missing exports required for some foreach backend

### PR DESCRIPTION
**Pull request by lepennec**
I've stumbled upon a bug for some foreach backend (doFuture with multisession for instance...). There are some missing exports in  workflows.R. It seems that completing the list as proposed below fix this issue.

### CODE REVIEW

**Comment by freezby** [comment]
I had the same problem using doMPI on a cluster of two nodes (localhost and one remote computer)
But to get things working I had to complete the export variable in a different way : 
  export <- c("optimism_xy", "requireNamespaceQuietStop","subset_x","pred_failed",
              "model_failed", "fail_warning", "fill_failed_pred", "fill_failed_prob",
              "trim_values", "outcome_conversion", "flatTable", "ppOpts", "createModel",
              "predictionFunction","probFunction"
              )

**Comment by lepennec** [comment]
OK. It looks like my list should be enlarged...

**Comment by brnleehng** [comment]
I had a similar issue with doAzureParallel, it seems that all of the internal functions will need to be 
in the export list since it depends on what caret function you are using 

#743

**Comment by brnleehng** [comment]
I ran one of our samples codes. Installed your branch, It works for me. 

library(DAAG)
library(caret)

set.seed(998)
inTraining <- createDataPartition(spam7$yesno, p = .75, list = FALSE)
training <- spam7[ inTraining,]
testing  <- spam7[-inTraining,]

fitControl <- trainControl(## 10-fold cross validation
                           method = "repeatedcv",
                           number = 10,
                           ## repeat 10 times
                           repeats = 10,
                           classProbs = TRUE,
                           summaryFunction = twoClassSummary,
                           search = "random",
                           ## run on the parallel backend
                           allowParallel = TRUE)

rf_fit <- train(
                 yesno ~ .,
                 data = training,
                 method = "rf",
                 metric = "ROC",
                 tuneLength = 30,
                 trControl = fitControl)

rf_fit

**Comment by topepo** [comment]
Thanks for fixing this. I run a bunch of tests using `doMC`. I'll add some more for `doParallel`. The issue is somewhat OS dependent (and cluster type dependent) too.

**Comment by topepo** [comment]
@brnleehng have you tested these updates on `doAzureParallel`? I'm getting a release together and it would be good to have confirmation. 

@lepennec Anything else that you think needs to happen?

**Comment by lepennec** [comment]
I expect that if we cover sufficient different backends, which seems to be the case, we should not have more surprise...

**Pull request merged**
