### PR TITLE
Glmnet varimp fix 2

### PR DESCRIPTION
**Pull request by strongh**
See previous thread: https://github.com/topepo/caret/pull/173

### CODE REVIEW

**Comment by strongh** [comment]
The Travis error also occurs on master.

**Comment by zachmayer** [comment]
Yup.  @topepo it looks like [our builds are failing on master](https://travis-ci.org/topepo/caret/jobs/72000592).  The relevant errors:
```{bash}
checking dependencies in R code ... WARNING
'::' or ':::' import not declared from: ‘rARPACK’
```
```{bash}
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
         warning = function(c) invokeRestart("muffleWarning"))
  2: eval(code, new_test_environment)
  3: eval(expr, envir, enclos)
  4: caret:::parse_sampling(i) at test_sampling_options.R:14
  5: checkInstall(pkgs)
  6: stop()
  
  testthat results ================================================================
```

The warning is solved with a simple addition of `rARPACK` to imports.  The error looks like a test failure introduced in ["added package checks for resampling"](https://github.com/topepo/caret/commit/73fda4673613c72aec7f547d45aef12ca5a44c90)

The error occurs in the [test_sampling_options.R](https://github.com/topepo/caret/blob/60788dbdf260a0750075b628edbbef1c7ce1a8c3/pkg/caret/tests/testthat/test_sampling_options.R#L14) test.

**Comment by topepo** [comment]
@strongh Sorry for taking so long to merge this in. Can you sync your PR and resolve any conflicts?

**Comment by strongh** [comment]
@topepo looks like it worked.

**Comment by topepo** [comment]
Can you remove  the`RData` file from the PR?

**Comment by strongh** [comment]
@topepo it has been made so.

**Comment by topepo** [comment]
`git` is fighting me on merging this. I just added the files and committed (see note above) and added your contribution to the NEWS file. You can delete the PR. 

Thanks for the fix!

**Comment by strongh** [comment]
:+1:

**Pull request closed without merging**
