### PR TITLE
Prevent duplicates in discrete tune grids

### PR DESCRIPTION
**Pull request by dashaub**
Prevent duplicate tuning parameter combinations in discrete random grids. There are probably other models that need this too, but I only looked at the models that I frequently use.

### CODE REVIEW

**Comment by topepo** [comment]
Instead, can you make this change to `train.default` right after the grid is created? I'd add it before the line 

```r
## Check to make sure that there are tuning parameters in some cases
```

and add `out[!duplicated(out), ,drop = FALSE]`. 

Also, please update the NEWS file.

**Comment by dashaub** [comment]
@topepo will do. I believe we can then also remove the checks for duplicates `out <- out[!duplicated(out),]` in all the other [model files](https://github.com/topepo/caret/search?q=duplicated%28out%29&unscoped_q=duplicated%28out%29) too, right?

**Comment by topepo** [comment]
> I believe we can then also remove the checks for duplicates `out <- out[!duplicated(out),]` in all the other [model files](https://github.com/topepo/caret/search?q=duplicated%28out%29&unscoped_q=duplicated%28out%29) too, right?

Yep. 

Thanks

**Comment by dashaub** [comment]
Done. I think I got them all:
```
$ grep 'duplicated(out)' files/*.R
$ grep 'duplicated(out)' deprecated/*.R
```

**Comment by dashaub** [comment]
@topepo Anything else you'd like on this?

**Comment by topepo** [comment]
Thanks

**Pull request merged**
