### PR TITLE
Prefix predict for every kernlab use

### PR DESCRIPTION
**Pull request by lepennec**
Dear Max,

it seems that the predict function has to be explicitly prefixed when using kernlab otherwise NAs are prediicted...

Erwan

### CODE REVIEW

**Comment by topepo** [comment]
Huh. That's odd. 

It's a good idea to do this anyway but do you can an example that I can test with?

Also, should they be class specific (e.g. `kernlab::predict.ksvm` instead of `kernlab::predict`)?

**Comment by lepennec** [comment]
It looks like kernlab::predict is a generic method so that specifying the
class is useless. Let me wrap up an example tomorrow...

**Comment by lepennec** [comment]
```
library(caret)
model <- train(Species ~ ., data = iris, method = "svmRadial")
predict(model)
```

**Comment by topepo** [comment]
Thanks

**Pull request merged**
